# Generated by Django 4.2.4 on 2023-08-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
